# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-12 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(max_length=256, verbose_name='train_id')),
                ('start', models.CharField(max_length=256, verbose_name='start')),
                ('dest', models.CharField(max_length=256, verbose_name='dest')),
                ('time', models.CharField(max_length=256, verbose_name='time')),
            ],
        ),
    ]
