# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-18 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171118_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='date',
            field=models.CharField(default='', max_length=256, verbose_name='date'),
        ),
    ]
